# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '第三方地图的使用-高德' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 第三方地图的使用-高德
  pod 'AMap2DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'

  target '第三方地图的使用-高德Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '第三方地图的使用-高德UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
