# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target '一个完整的网络请求案例' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 一个完整的网络请求案例
  pod 'Kingfisher'
  pod 'SnapKit'

  target '一个完整的网络请求案例Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '一个完整的网络请求案例UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
