# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alamofire的基本使用' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alamofire的基本使用
  pod 'Alamofire'
  target 'Alamofire的基本使用Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Alamofire的基本使用UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
