# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFN上传文件' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AFN上传文件
  pod 'Alamofire', '~> 5.2'

  target 'AFN上传文件Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFN上传文件UITests' do
    # Pods for testing
  end

end
